apps/site/urls.py
from django.urls import path, re_path
from .views import *

urlpatterns = [
    path('', WelcomeView.as_view(), name='home'),
    path('rules', RulesView.as_view(), name='rules'),
    re_path(r'^check/?((in)|(out)|(message))?$', CheckinView.as_view(), name='checkin'),
    path('<slug:event>', EventInfoView.as_view(), name='event-info'),
    path('<slug:event>/register', AttendeeRegistrationView.as_view(), name='attendee-registration'),
]

grupyrn_meetup/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework import routers


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('registration.urls')),
    path('api/', include('api.urls')),
    path('api/', include('rest_framework.urls', namespace='rest_framework'))
]

jararaca/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from rest_framework import routers


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.site.urls')),
    path('api/', include('apps.api.urls')),
    path('api/', include('rest_framework.urls', namespace='rest_framework'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

apps/api/models.py
import json
import traceback
import uuid
from datetime import date, datetime, timedelta
from io import BytesIO

from PIL import Image
from colorful.fields import RGBColorField
from django.contrib.auth import get_user_model
from django.db import models
from django.db.models import Q
from django.urls import reverse
from django.utils import timezone
from django.utils.formats import date_format
from django.utils.html import format_html
from django.utils.safestring import mark_safe
from django.utils.translation import gettext_lazy as _

from apps.api.helpers import date_range_format, scale_to_width


class MemberInfo(object):
    def __init__(self, name, email, cpf=None):
        self.name = name
        self.email = email
        self.cpf = cpf

    def to_json(self):
        func = lambda o: {k: v for k, v in o.__dict__.items()
                          if v is not None}

        return json.dumps(self, default=func,
                          sort_keys=True)


class Attendee(models.Model):
    uuid = models.UUIDField(primary_key=True, editable=False, default=uuid.uuid4)
    event = models.ForeignKey('Event', verbose_name=_('event'), on_delete=models.CASCADE)
    name = models.CharField(_('name'), max_length=500)
    email = models.EmailField(_('email'), max_length=50)
    cpf = models.CharField(_('CPF'), max_length=11)
    share_data_with_partners = models.BooleanField(_('share data with partners'), default=False)
    date = models.DateTimeField(_('date'), auto_now_add=True)
    want_to_be_an_organizer = models.BooleanField(_('want to be an organizer'), default=False)
    permission_to_be_an_organizer = models.BooleanField(_('permission to be an organizer'), default=False)

    @property
    def presence_percentage(self):
        event_time = 0
        for day in self.event.eventday_set.all():
            event_time += (datetime.combine(date.min, day.end) - datetime.combine(date.min, day.start)).seconds

        checked_time = 0
        for checked_day in self.eventdaycheck_set.filter(exit_date__isnull=False):
            checked_time += (checked_day.exit_date - checked_day.entrance_date).seconds

        result = checked_time * 100 / event_time

        return result

    def formated_presence_percentage(self):
        if self.presence_percentage > 100:
            return '100%'
        return '%d%%' % self.presence_percentage

    formated_presence_percentage.short_description = _('presence percentage')

    def is_eligible_to_certificate(self):
        return self.presence_percentage >= self.event.certificate_minimum_time

    is_eligible_to_certificate.short_description = _('eligible to certificate')
    is_eligible_to_certificate.boolean = True

    def is_eligible_to_certificate_org(self):
        return self.permission_to_be_an_organizer and self.presence_percentage > 0

    is_eligible_to_certificate_org.short_description = _('eligible to organization certificate')
    is_eligible_to_certificate_org.boolean = True

    def __str__(self):
        return f'{self.name} ({self.uuid})'

    class Meta:
        verbose_name = _('attendee')
        verbose_name_plural = _('attendees')

class Event(models.Model):
    name = models.CharField(_('name'), max_length=500)
    description = models.TextField(_('description'), blank=True)
    place = models.CharField(_('place'), max_length=500)
    latitude = models.FloatField(_('latitude'))
    longitude = models.FloatField(_('longitude'))
    organizers = models.CharField(_('organizers'), max_length=500)
    created_by = models.ForeignKey(get_user_model(), _('created by'), null=True)
    slug = models.SlugField(unique=True)
    content_link = models.URLField(_('content link'), null=True, blank=True)
    certificate_model = models.ForeignKey('CertificateModel', related_name='%(class)s_certificate_model', verbose_name=_('certificate model'), null=True, blank=True, on_delete=models.PROTECT)
    certificate_hours = models.IntegerField(_('certificate hours'), default=4)
    certificate_minimum_time = models.IntegerField(_('minimum length of stay for certificate'),
                                                   help_text=_('Percentage from total time'), default=75)
    certificate_org = models.ForeignKey('CertificateModel', related_name='org_certificate_model', verbose_name=_('organization certificate model'), null=True, blank=True, on_delete=models.PROTECT)
    certificate_hours_org = models.IntegerField(_('organization certificate hours'), default=10)

    closed_registration = models.BooleanField(_('closed registration'), default=False)

    @property
    def formated_duration(self):
        hours = self.certificate_hours
        return _('%s hours') % (hours,) if hours != 1 else _('%s hour') % (hours,)

    @property
    def formated_dates(self):
        dates = self.eventday_set.values_list('date', flat=True)
        return date_range_format(dates)

    @property
    def date(self):
        return self.eventday_set.order_by('date').values_list('date', flat=True).all()

    @property
    def start(self):
        day = self.eventday_set.order_by('date').first()
        return datetime.combine(day.date, day.start)

    @property
    def end(self):
        day = self.eventday_set.order_by('-date').first()
        return datetime.combine(day.date, day.end)

    @property
    def current_day(self):
        return self.eventday_set.get(date=date.today())

    @staticmethod
    def current_events(tolerance: timedelta):
        now = datetime.now()
        tolerance = timedelta(minutes=60)
        now_plus = now + tolerance
        now_minus = now - tolerance

        return Event.objects.filter(
            (
                    (Q(eventday__date=now.date()) & Q(eventday__start__lte=now.time()) & Q(
                        eventday__end__gte=now.time())) |
                    (Q(eventday__date=now.date()) & Q(eventday__start__lte=now_plus.time()) & Q(
                        eventday__end__gte=now.time())) |
                    (Q(eventday__date=now.date()) & Q(eventday__start__lte=now.time()) & Q(
                        eventday__end__gte=now_minus.time()))
            ) |
            (
                    (Q(eventday__date=now.date()) & Q(eventday__subevent__isnull=False))
            )
            # | (
            #         (Q(eventday__date=now.date()) & Q(eventday__subevent__start__lte=now.time()) & Q(
            #             eventday__subevent__end__lte=now.time())) |
            #         (Q(eventday__date=now.date()) & Q(eventday__subevent__start__lte=now_plus.time()) & Q(
            #             eventday__subevent__end__lte=now.time())) |
            #         (Q(eventday__date=now.date()) & Q(eventday__subevent__start__lte=now.time()) & Q(
            #             eventday__subevent__end__lte=now_minus.time()))
            # )


        )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('event')
        verbose_name_plural = _('events')


class EventDay(models.Model):
    event = models.ForeignKey('Event', verbose_name=_('event'), on_delete=models.CASCADE)
    date = models.DateField(_('date'))
    start = models.TimeField(_('start time'))
    end = models.TimeField(_('end time'))

    @property
    def is_last(self):
        return self == self.event.eventday_set.latest('date')

    @mark_safe
    def schedule_link(self):
        if self.id:
            changeform_url = reverse(
                'admin:api_eventday_change', args=(self.id,)
            )
            return '<a href="%s" target="_blank">%s</a>' % (changeform_url, _('change schedule').title())
        return u''

    schedule_link.short_description = ''

    def __str__(self):
        return f'{self.event.name} - {date_format(self.date, format="SHORT_DATE_FORMAT", use_l10n=True)}'

    class Meta:
        verbose_name = _('event day')
        verbose_name_plural = _('event days')
        unique_together = ('event', 'date')


class EventSchedule(models.Model):
    event = models.ForeignKey('EventDay', verbose_name=_('event day'), on_delete=models.CASCADE)
    start = models.TimeField(_('start time'))
    end = models.TimeField(_('end time'))
    title = models.CharField(_('title'), max_length=150)
    place = models.CharField(_('place'), max_length=150, blank=True)
    description = models.TextField(_('description'), blank=True)
    authors = models.CharField(_('authors'), max_length=500, blank=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = _('event schedule')
        verbose_name_plural = _('event schedules')
        ordering = ['start']


class EventDayCheck(models.Model):
    attendee = models.ForeignKey('Attendee', verbose_name=_('attendee'), on_delete=models.CASCADE)
    event_day = models.ForeignKey('EventDay', verbose_name=_('event day'), on_delete=models.CASCADE)
    entrance_date = models.DateTimeField(_('entrance date/time'), auto_now_add=True)
    exit_date = models.DateTimeField(_('exit date/time'), null=True)

    @property
    def attendee_name(self):
        return self.attendee.name

    @property
    def time_passed(self):
        return self.exit_date - self.entrance_date if self.exit_date else None

    def event(self):
        return self.event_day.event

    time_passed.fget.short_description = _('permanence time')

    def __str__(self):
        return f'{self.attendee.name} ({self.event_day.event.name} - ' \
            f'{date_format(self.event_day.date, format="SHORT_DATE_FORMAT", use_l10n=True)})'

    def checkout(self):
        if not self.exit_date:
            self.exit_date = timezone.now()
            self.save()

    class Meta:
        verbose_name = _('event day check')
        verbose_name_plural = _('event day checks')


class SubEvent(models.Model):
    event_day = models.ForeignKey('EventDay', verbose_name=_('event day'), on_delete=models.CASCADE)
    start = models.TimeField(_('start time'))
    end = models.TimeField(_('end time'))

apps/site/models.py
from datetime import datetime

from django.db import models


# Create your models here.

apps/site/forms.py
from django import forms
from localflavor.br.forms import BRCPFField
from django.utils.translation import gettext_lazy as _
from apps.api.models import Attendee


class AttendeeForm(forms.ModelForm):
    cpf = BRCPFField(required=False, help_text=_('Optional. Numbers only. Only if you wish to add this information in '
                                                 'the certificate.'))
    want_to_be_an_organizer = forms.BooleanField(label=_('I want to request to be an event organizer'), required=False)
    authorize = forms.BooleanField(required=True, label=_('I authorize the use of my data exclusively for my '
                                                          'identification at this GruPy-RN event.'))
    share_data_with_partners = forms.BooleanField(label=_('I also authorize to share my name and e-mail information '
                                                          'with GruPy-RN partners.'), required=False)

    class Meta:
        model = Attendee
        fields = ('name', 'email', 'cpf', 'want_to_be_an_organizer', 'authorize', 'share_data_with_partners')

apps/site/views.py
import base64
from datetime import date

from django.contrib import messages
from django.http import Http404
from django.shortcuts import render, get_object_or_404
from django.utils.datastructures import OrderedSet
from django.utils.translation import gettext_lazy as _
from django.views.generic import FormView
from django.views.generic import TemplateView

from apps.api import senders
from apps.api.models import Event, Attendee
from apps.site.forms import AttendeeForm


class WelcomeView(TemplateView):
    template_name = 'site/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['future_events'] = OrderedSet(Event.objects.filter(eventday__date__gte=date.today()).order_by(
            'eventday__date'))
        context['past_events'] = OrderedSet(Event.objects.filter(eventday__date__lte=date.today()).order_by(
            '-eventday__date'))
        return context


class EventInfoView(TemplateView):
    template_name = 'site/event.html'

    def get(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        context.update(event=get_object_or_404(Event, slug=context['event']))
        return self.render_to_response(context)


class CheckinView(TemplateView):
    template_name = 'site/checkin.html'

    def get(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        return self.render_to_response(context)


class RulesView(TemplateView):
    template_name = 'site/rules.html'


class AttendeeRegistrationView(FormView):
    template_name = 'site/form.html'
    form_class = AttendeeForm

    success_url = '/thanks/'
    
    def get(self, request, *args, **kwargs):
        event = OrderedSet(Event.objects.filter(slug=kwargs['event'], eventday__date__gte=date.today(),
                                                closed_registration=False))
        if not len(event):
            raise Http404

        event = list(event)[0]

        return self.render_to_response(self.get_context_data(event=event))

    def form_valid(self, form):
        event = OrderedSet(Event.objects.filter(slug=self.request.POST['event'], eventday__date__gte=date.today(),
                                                closed_registration=False))
        if not len(event):
            raise Http404

        event = list(event)[0]

        attendee = form.instance
        attendee.event = event
        defaults = form.cleaned_data
        authorize = defaults.pop('authorize')
        
        if not authorize:
            messages.error(self.request, _('Registration failed.'))
            return self.form_invalid(form)

        user, created = Attendee.objects.get_or_create(
            event=event,
            email=attendee.email,
            defaults=form.cleaned_data
        )
        try:
            qr_data = senders.send_registration_mail(user, event)
            context = self.get_context_data(qr_code=base64.b64encode(qr_data).decode('ascii'))
            if created:
                return render(self.request, 'site/thanks.html', context)
            return render(self.request, 'site/duplicate.html', context)
        
        except Exception as e:
            print(e)
            messages.error(self.request, _('Registration failed.'))
            return self.form_invalid(form)

    def form_invalid(self, form):
        event = OrderedSet(Event.objects.filter(slug=self.request.POST['event'], eventday__date__gte=date.today(),
                                                closed_registration=False))
        if not len(event):
            raise Http404
        event = list(event)[0]
        return self.render_to_response(self.get_context_data(form=form, event=event))

apps/site/templates/site/base.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1"/>
  <title>GruPy-RN</title>

  <!-- CSS  -->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
  <link href="{% static 'css/materialize.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>
  <link href="{% static 'css/../../static/css/style.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>
  {% block styles %}{% endblock styles %}
  <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}" type="image/x-icon">
</head>
  <body>

    <header>
      {% include 'site/menu.html' %}
    </header>

    <main>
      {% block content %}
      {% endblock content %}
    </main>

    <footer class="page-footer">
      {% include 'site/footer.html' %}
    </footer>

    <!--  Scripts-->
    <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script src="{% static 'js/materialize.js' %}"></script>
    <script src="{% static 'js/init.js' %}"></script>
    {% block scripts %}{% endblock scripts %}

</body>
</html>

apps/site/templates/site/checkin.html
{% load render_bundle from webpack_loader %}
{% load staticfiles %}
{% load i18n %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{% trans "Jararaca - GruPy-RN Event and Check-in System" %}</title>
    <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}" type="image/x-icon">
    <!-- Webpack rendered CSS -->
    {% render_bundle 'main' 'css' %}
</head>

<body class="bg-light">
<div class="container">
    <div class="py-4 text-center">
        <img class="d-block mx-auto mb-2" src="{% static 'img/logo_small.png' %}" alt="GruPy-RN Logo" >
    </div>
    <div id="root"></div>
</div>

<!-- Webpack rendered JS -->
{% render_bundle 'main' 'js' %}
</body>
</html>

apps/site/templates/site/duplicate.html
{% extends 'site/base.html' %}
{% load static %}
{% load i18n %}


{% block content %}
<section class="teste">    
  <div class="container">
    <div class="row center">
           <div class="col s12 m7">
              <h1 class="center-align h1-header">Credenciais reenviadas com sucesso!</h1>
              <p class="center-align p-thanks">Você já efetuou seu cadastro nesse evento!
                  Estamos reenviando o QRCode para seu e-mail, e lembre-se:
                  Este QR-Code é o seu passaporte de entrada
                  para este evento do GruPy-RN, leve-o com você.</p>
          </div>
          <div class="col s12 m5">
              <img src="data:image/png;base64,{{ qr_code }}" class="responsive-img qrcode-size"/>
          </div>
    </div>
  </div>
</section>
{% endblock content %}

apps/site/templates/site/event.html
{% extends 'site/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load i18n %}

{% block content %}

  <section>
    <div class="container">
      <div class="row">
        <h2 class="left">{{ event.name }}</h2>
        <div class="col s12 m12">
          <div>
            <p>{{ event.description }}</p>
          </div>
          {% if not event.closed_registration %}
            <a class="waves-effect waves-light btn yellow darken-2 btn-large" href="{% url 'attendee-registration' event.slug %}">{% trans "Register" %}</a>
          {% endif %}

          {% for day in event.eventday_set.all %}
            <div>
              <h4>{% trans "Schedule" %} - {{ day.date|date:'SHORT_DATE_FORMAT' }}</h4>
              <ul class="collection">
                {% for item in day.eventschedule_set.all %}
                  <li class="collection-item avatar">
                    <span class="title"></span>
                    <p>{{ item.title }}<br>
                      <span class="yellow-text text-darken-3">{{ item.start }}h - {{ item.end }}h</span>
                    </p>
                    {% if item.authors %}
                      <p class="light-blue-text text-lighten-2">{{ item.authors }}</p>
                    {% endif %}
                  </li>
                {% endfor %}
              </ul>
            </div>
          {% endfor %}
        </div>

        <div class="col s12 m6">
          <h4>{% trans "Place" %}</h4>
          <div id="map" style="width:100%;height:400px;"></div>
        </div>
      </div>
    </div>
  </section>
{% endblock content %}

{% block scripts %}
  <script>
      function myMap() {
          var mapCanvas = document.getElementById("map");
          var myLatLng = {'lat': {{ event.latitude|stringformat:"f" }}, 'lng': {{ event.longitude|stringformat:"f" }}};
          var mapOptions = {
              center: new google.maps.LatLng(myLatLng),
              zoom: 14
          };
          var map = new google.maps.Map(mapCanvas, mapOptions);

          var marker = new google.maps.Marker({
            position: myLatLng,
            map: map,
            title: "{{ event.name }}"
          });

      }
  </script>

  <script src="https://maps.googleapis.com/maps/api/js?key={{ GOOGLE_MAPS_API_KEY }}&callback=myMap"></script>

{% endblock scripts %}

apps/site/templates/site/footer.html
{% load static %}
{% load i18n %}

<div class="container">
  <div class="row">
    <div class="col l6 s12">
      <h5 class="white-text">{% trans "Jararaca - GruPy-RN Event and Check-in System" %}</h5>
      <p class="grey-text text-lighten-4">{% trans "From developers to the community." %}</p>
    </div>
    <div class="col l4 offset-l2 s12">
      <h5 class="white-text">{% trans "Social networks" %}</h5>
      <div class="categories-container pin-top">
        <ul class="categories db fa-ul">
          <li class="fa-li social-network-li"><a class="grey-text text-lighten-3" href="https://www.facebook.com/grupyrn/" target="_blank"><i class="fab fa-facebook-square fa-2x"></i></a></li>
          <li class="fa-li social-network-li"><a class="grey-text text-lighten-3" href="https://www.instagram.com/grupyrn/" target="_blank"><i class="fab fa-instagram fa-2x"></i></a></li>
          <li class="fa-li social-network-li"><a class="grey-text text-lighten-3" href="https://t.me/grupyrn" target="_blank"><i class="fab fa-telegram fa-2x"></i></a></li>
          <li class="fa-li social-network-li"><a class="grey-text text-lighten-3" href="https://www.twitter.com/grupy_rn" target="_blank"><i class="fab fa-twitter-square fa-2x"></i></a></li>
        </ul>
      </div>      
    </div>
  </div>
</div>
<div class="footer-copyright">
  <div class="container">
    2019 GruPy-RN
  </div>
</div>

apps/site/templates/site/form.html
{% extends 'site/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load i18n %}

{% block content %}
  <div class="container">
    <h2 class="center-align h1-header">{{ event.name }}</h2>
    <p class="center-align p-form">{% trans "Register now!" %}</p>
  </div>


<div class="container cont-padding-top">

  {% if form.errors %}
    <div class="row">
      <blockquote>
        <h5>{% trans "Correct the following error(s):" %}</h5>
        <ul>
          {% for field in form %}
            {% if field.errors %}
              {% for error in field.errors %}
                <li>{{ error|escape }}</li>
              {% endfor %}
            {% endif %}
          {% endfor %}
        </ul>
        {% if form.non_field_errors %}
          {{ form.non_field_errors }}
        {% endif %}

      </blockquote>
    </div>
  {% endif %}

  <div class="row">
    <form class="col s12" method="post" action="">
      <input type="hidden" name="event" value="{{ event.slug }}">
      
      {% crispy form %}

      <br /><br />
      <div class="row">
        <div class="input-field col s12">
          <button class="btn waves-effect waves-light yellow darken-2" type="submit" name="action">Enviar
            <i class="material-icons right">send</i>
          </button>
        </div>
      </div>
    </form>
  </div>
</div>

{% endblock content %}

<!--  Scripts-->
<script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
<script src="{% static 'js/materialize.js' %}"></script>
<script src="{% static 'js/init.js' %}"></script>

</body>
</html>

apps/site/templates/site/index.html
{% extends 'site/base.html' %}
{% load static %}
{% load i18n %}

{% block content %}

  {% include 'site/parallax.html' %}


  <section>
    <div class="container">
      <div class="row">

        <h1 id="future-events" class="center-align black-title scrollspy">{% trans "Future events" %}</h1>

        {% for event in future_events %}
          <div class="col s12 m6">
            <div class="card blue-card darken-1">
              <div class="card-content white-text">
                {% if event.certificate_model %}
                  <span class="card-title">{{ event.name }} 📜</span>
                {% else %}
                  <span class="card-title">{{ event.name }}</span>
                {% endif %}
                <p>{{ event.place }}</p>
                <p>{% for date in event.date %}{{ date|date:'SHORT_DATE_FORMAT' }}{% if not forloop.last %},
                {% endif %}{% endfor %}</p>
              </div>
              <div class="card-action">
                {% if not event.closed_registration %}
                  <a class="yellow-link" href="{% url 'attendee-registration' event.slug %}">{% trans "Register" %}</a>
                {% endif %}
                <a class="yellow-link" href="{% url 'event-info' event.slug %}">{% trans "More info" %}</a>
              </div>
            </div>
          </div>
        {% empty %}
          <div class="center">
            <p>{% trans "Coming soon." %}</p>
            <p>{% trans "In the meantime, take a look at the "%} <a href="/#past-events">{% trans "previous events!" %}</a></p>
          </div>
        {% endfor %}

      </div>
    </div>
  </section>

  <section class="about">
    <div class="container ">
      <div class="row">
        <div class="s12">
          <h1 id="who-we-are" class="center-align black-title scrollspy">{% trans "Who we are" %}</h1>
          <p>O GruPy - RN é a comunidade de Python do Rio Grande do Norte, tem como objetivo promover um ambiente
            amistoso, de boa convivência, inclusivo e livre de intimidação, onde todas as pessoas são bem-vindas e a
            civilidade é exigida.</p>
          <p>Com esta finalidade, a organização do evento atua para garantir um ambiente com essas qualidades.</p>
        </div>
      </div>
    </div>
  </section>

  <section>
    <div class="container">
      <div class="row">
        <div class="col s12">

          <h1 id="past-events" class="center-align black-title scrollspy">{% trans "Past events" %}</h1>

        {% if past_events %}
          <table class="highlight centered ">
            <thead>
            <tr>
              <th>{% trans "Event" %}</th>
              <th>{% trans "Date" %}</th>
              <th>{% trans "Place" %}</th>
              <th>{% trans "Content" %}</th>
            </tr>
            </thead>
            <tbody>

            {% for event in past_events %}
              <tr>
                <td>{{ event.name }}</td>
                <td>{% for date in event.date %}{{ date|date:'SHORT_DATE_FORMAT' }}{% if not forloop.last %},
                {% endif %}{% endfor %}</td>
                <td>{{ event.place }}</td>
                <td>
                  {% if event.content_link %}
                    <a href="{{ event.content_link }}" target="_blank">{% trans 'Open' %}</a>
                  {% else %}
                    {% trans "Unavailable" %}
                  {% endif %}
                </td>
              </tr>
            {% endfor %}

            </tbody>
          </table>
        {% else %}
          <p>{% trans "There are no past events to show." %}</p>
        {% endif %}

        </div>
      </div>
    </div>
  </section>

{% endblock content %}

apps/site/templates/site/menu.html
{% load static %}
{% load i18n %}

<div class="navbar-fixed">
  <nav class="white" role="navigation">
    <div class="nav-wrapper container">
      <a id="logo-container" href="{% url 'home' %}" class="brand-logo"><img class="center-logo"
                                                                             src="{% static '/img/../../static/img/logo.png' %}"></a>
      <ul class="right hide-on-med-and-down">
        <li><a href="{% url 'home' %}#future-events">{% trans "Future events" %}</a></li>
        <li><a href="{% url 'home' %}#who-we-are">{% trans "Who we are" %}</a></li>
        <li><a href="{% url 'home' %}#past-events">{% trans "Past events" %}</a></li>
        <li><a href="{% url 'rules' %}">{% trans "Rules" %}</a></li>
      </ul>
      <a href="#" data-target="nav-mobile" class="sidenav-trigger"><i class="material-icons">menu</i></a>
    </div>
  </nav>
</div>

<div class="mobile-menu">
  <ul id="nav-mobile" class="sidenav">
    <li><a href="/#future-events">{% trans "Future events" %}</a></li>
    <li><a href="/#who-we-are">{% trans "Who we are" %}</a></li>
    <li><a href="/#past-events">{% trans "Past events" %}</a></li>
    <li><a href="{% url 'rules' %}">{% trans "Rules" %}</a></li>    
  </ul>
</div>

apps/site/templates/site/parallax.html
{% load static %}

<div class="container-header valign-wrapper">
      <div class="row">
        <!-- <h1 class="center-align h1-welcome">Venha participar dos meetup do GruPy-RN</h1> -->
      </div>
    </div>

apps/site/templates/site/rules.html
{% extends 'site/base.html' %}
{% load static %}
{% load i18n %}


{% block content %}
<section>
    <div class="container">
        <div class="row">
            <div class="col">
                <h1 class="center-align h1-header">Regras</h1>
                <ul class="rule">
                    <li>O participante é o único responsável por seus dados
                        informados na inscrição no evento.
                     </li>
                    <li>
                        O participante deverá comparecer ao evento com o QR-code
                        em mãos, seja no celular ou  impresso.
                    </li>
                    <li>
                        O participante que não levar QR-code poderá participar
                        do evento, mas não receberá certificado de participação.
                    </li>
                    <li>
                        O participante é o único responsável pelo seu próprio
                        check-in e check-out.
                    </li>
                    <li>
                        O participante receberá o certificado de participação
                        somente se seu tempo de permanência for igual ou
                        superior a 75% do período do evento, entre o check-in
                        e check-out.
                    </li>
                    <li>
                        A organização se isenta realizar de qualquer alteração
                        cadastral de participante, incluindo check-in e
                        check-out. Não insista.
                    </li>
                </ul>
            </div>
        </div>
    </div>
</section>

{% endblock %}